import 'package:flutter/material.dart';

class AppLanguage extends ChangeNotifier {
  String _currentLanguage = 'az';

  String get currentLanguage => _currentLanguage;

  void changeLanguage(String langCode) {
    if (_currentLanguage != langCode) {
      _currentLanguage = langCode;
      notifyListeners();
    }
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'az': {
      'app_title': 'WorkSpot',
      'tag': '📍 İş Elanları Xəritəsi',
      'subtitle': 'Xəritə üzərindən sizə ən yaxın iş elanlarını kəşf edin, vakansiyaları yerindəcə görün və bir kliklə müraciət edin.',
      'phone_login': 'Telefon Nömrəsi ilə Giriş',
      'or_social': 'və ya sosial şəbəkə ilə',
      'guest_login': 'Hesabsız davam et (Xəritəni kəşf et)',
      'terms': 'Daxil olmaqla WorkSpot-un İstifadə Şərtlərini və Məxfilik Siyasətini qəbul etdiyinizi təsdiqləyirsiniz.',
      'select_language': 'Tətbiq Dilini Seçin',
      'search_hint': 'Vakansiya və ya şirkət axtarın...',
      'all': 'Bütün Vakansiyalar',
      'cat_catering': 'Restoran & Kafeler',
      'cat_it': 'İT & Proqramlaşdırma',
      'cat_sales': 'Satış & Marketinq',
      'cat_logistics': 'Logistika & Çatdırılma',
      'cat_customer_service': 'Müştəri Xidmətləri',
      'cat_construction': 'Tikinti & Təmir',
      'cat_education': 'Təhsil & Tədris',
      'cat_medicine': 'Səhiyyə & Tibb',
      'cat_beauty': 'Gözəllik & Salonda İş',
      'radius_text': 'km radiusda',
      'filter_title': 'Axtarış Filterləri',
      'reset': 'Sıfırla',
      'search_radius': 'Axtarış Radiusu:',
      'salary_range': 'Maaş Aralığı:',
      'job_modes': 'İş Rejimi:',
      'all_modes': 'Bütün Rejimlər',
      'full_time': 'Tam iş günü',
      'part_time': 'Yarım İş Qrafiki',
      'remote': 'Məsafədən (Remote)',
      'apply_now': 'Müraciət Et',
      'company_profile': 'Şirkət Profili',
      'salary_label': 'Əmək Haqqı:',
      'posted_label': 'Yayımlanıb:',
      'job_info': 'İş Barədə Məlumat:',
      'found_jobs': 'Tapılan Vakansiyalar',
      'no_jobs_found': 'Bu filterə uyğun vakansiya tapılmadı.',
      'applied_msg': 'vakansiyasına müraciətiniz göndərildi!',
      'satellite_mode': 'Peyk Rejimi',
      'vector_mode': 'Xəritə Rejimi',
      // PROFIL EKRANI SÖZLƏRİ:
      'profile_title': 'Şəxsi Kabinet',
      'cv_status': 'Rəqəmsal CV statusu',
      'update_cv': 'CV Faylını Yenilə',
      'stat_applications': 'Müraciətlər',
      'stat_cv_views': 'Baxılan CV-lər',
      'stat_favorites': 'Bəyənilənlər',
      'my_applications': 'Göndərdiyim Müraciətlər',
      'tab_all': 'Hamısı',
      'tab_reviewed': 'Baxılanlar',
      'tab_accepted': 'Qəbul Edilənlər',
      'no_applications_yet': 'Hələ ki heç bir vakansiyaya müraciət etməmisiniz.',
      'no_applications_sub': 'Xəritədə sizə yaxın iş elanlarını kəşf edin və CV-nizi bir kliklə göndərin.',
      'find_jobs_map': 'Xəritədə İş Axtar',
      'settings_title': 'Tənzimləmələr',
      'notifications_title': 'Vakansiya Bildirişləri',
      'settings_notifications': 'Bildirişlər',
      'notifications_nearby_subtitle': 'Yaxınlıqda yeni iş çıxdıqda bildiriş al',
      'dark_mode': 'Qaranlıq Rejim (Dark Mode)',
      'notifications': 'Bildirişlər',
      'all_notifications': 'Bütün bildirişlər',
      'unread_notifications': 'Oxunmamışlar',
      'mark_all_read': 'Hamısını oxunmuş et',
      'notifications_empty': 'Bildiriş tapılmadı',
      'notifications_unread_empty': 'Oxunmamış bildirişiniz yoxdur',
      'notification_application_title': 'CV-nizə baxıldı!',
      'notification_interview_title': 'Müsahibə Dəvəti 🎯',
      'notification_new_job_title': 'Ərazinizdə Yeni Vakansiya 📍',
      'notification_system_title': 'Sistem Bildirişi',
      'notification_application_message': '{company} şirkəti "{job}" vakansiyası üçün göndərdiyiniz müraciətə baxdı.',
      'notification_interview_message': '{company} şirkəti sizi "{job}" vakansiyası üzrə onlayn müsahibəyə dəvət edir.',
      'notification_new_job_message': 'Yaxınlığınızda (500m məsafədə) yeni "{job}" elanı yerləşdirildi.',
      'notification_system_message': 'WorkSpot tətbiqində profil məlumatlarınızı tamamlayaraq daha çox işəgötürənin diqqətini çəkə bilərsiniz.',
      'time_10_minutes': '10 dəq əvvəl',
      'time_2_hours': '2 saat əvvəl',
      'time_yesterday': 'Dünən',
      'time_3_days': '3 gün əvvəl',
      'logout': 'Hesabdan Çıx',
      'add_vacancy': 'Yeni Vakansiya Əlavə Et',
      'job_title_required': 'Vakansiya Adı *',
      'company_place_required': 'Şirkət / Məkan Adı *',
      'category_label': 'Kateqoriya',
      'job_type_label': 'İş Rejimi',
      'salary_required': 'Maaş (AZN) *',
      'shift_work': 'Növbəli',
      'daily_work': 'Gündəlik',
      'hourly_flexible': 'Saatlıq / Sərbəst',
      'remote_work': 'Uzaqdan (Remote)',
      'vip_publish': 'VIP Elan kimi yerləşdir',
      'vip_subtitle': 'Xəritədə qızılı rəngdə üst sırada göstərilir',
      'select_location': 'İş Məkanını Xəritədə Seçin (Xəritəyə toxunun):',
      'selected_coordinate': 'Seçilmiş kordinat:',
      'publish_vacancy': 'Vakansiyanı Dərc Et',
      'view_details': 'Ətraflı Bax',
      'city_baku': 'Bakı',
      'status_new': 'Yeni',
      'no_description': 'Vakansiya haqqında məlumat yoxdur.',
      'edit_profile': 'Profili Redaktə Et',
      // BİZNES / ÖDƏNİŞ EKRANI SÖZLƏRİ:
      'vip_biznes_button': 'VIP Biznes',
      'biznes_packages_title': 'WorkSpot Biznes & Paketlər',
      'biznes_packages_subtitle': 'VIP elanlar və Pro abunəlik',
      'checkout_title': 'Paket seçimi',
      'checkout_b2b_section': 'B2B VIP Paketlər',
      'checkout_pro_section': 'Pro Abunəlik',
      'pkg_single_vip_pin': 'Tək VIP Pin (həftəlik)',
      'pkg_pro_business': 'Pro Biznes Paketi (aylıq)',
      'pkg_enterprise': 'Enterprise Paket (aylıq)',
      'pkg_pro_subscription': 'Pro Abunəlik (aylıq)',
      'vip_days_suffix': 'gün VIP',
      'select_package': 'Paket seçin',
      'pay_with_pos': 'POS ilə ödə',
      'subscribe_now': 'Abunə ol',
      'payment_confirmed_title': 'Ödəniş təsdiqləndi',
      'receipt_package_label': 'Paket',
      'receipt_amount_label': 'Məbləğ',
      'receipt_method_label': 'Ödəniş üsulu',
      'receipt_transaction_label': 'Əməliyyat №',
      'receipt_vip_expiry_label': 'VIP bitmə tarixi',
      'download_receipt': 'Qəbzi yüklə',
      'request_e_invoice': 'E-Qaimə sorğula',
      'close_label': 'Bağla',
      'receipt_download_placeholder': 'Qəbz yükləmə tezliklə əlçatan olacaq.',
      'e_invoice_placeholder': 'E-Qaimə sorğusu qeydə alındı.',
      'payment_method_local_pos': 'Yerli POS (Kart)',
      'payment_method_apple_iap': 'Apple In-App Purchase',
      'payment_method_google_iap': 'Google In-App Purchase',
      'payment_success_message': 'Ödəniş uğurla tamamlandı.',
      'payment_failed_prefix': 'Ödəniş tamamlanmadı:',
      // ROL SEÇİMİ / BİZNES PANEL SÖZLƏRİ:
      'select_role_title': 'Tətbiqdən necə istifadə edəcəksiniz?',
      'select_role_subtitle': 'Profil növünü seçərək davam edin',
      'role_candidate_title': 'İş Axtarıram',
      'role_candidate_desc': 'Xəritədə vakansiyaları kəşf edin və 1 kliklə müraciət edin',
      'role_employer_title': 'İşçi Axtarıram / Şirkət',
      'role_employer_desc': 'Vakansiya yerləşdirin və uyğun namizədləri tapın',
      'business_dashboard': 'Sahibkar Paneli',
      'post_new_job': '+ Yeni Vakansiya Yerləşdir',
      'my_active_jobs': 'Aktiv Elanlarım',
      'analytics_title': 'Namizəd Analitikası',
      'total_views': 'Ümumi Baxış',
      'total_applications': 'Müraciət Sayı',
      'contact_views': 'Əlaqə Baxışları',
      'upgrade_for_analytics': 'Tam analitika və baxış sayı üçün Pro Business paketinə keçin',
      'switch_to_map': 'Xəritə Görüntüsünə Keç',
      'plan_standard_name': 'Standart (Pulsuz)',
      'plan_standard_f1': '📍 Xəritədə elanları kəşf etmək',
      'plan_standard_f2': '🎬 Müraciət etmək üçün reklama baxış',
      'plan_pro_name': 'Pro (\$3.99 / ay)',
      'plan_pro_f1': '🚫 Tam Reklamsız təcrübə (No Ads)',
      'plan_pro_f2': '⚡ Ani 1-kliklə müraciət',
      'plan_pro_f3': '🔔 Yeni vakansiyalar üçün ani bildirişlər',
      'plan_vip_name': 'VIP Pin (\$8.99 / həftə)',
      'plan_vip_f1': '👑 Xəritədə parlayan Qızılı VIP Pin',
      'plan_vip_f2': '🔝 Axtarış və siyahıda ən yuxarıda görünmə',
      'plan_vip_f3': '📈 3x daha çox müraciət şansı',
      'plan_biz_name': 'Pro Business (\$22.99 / ay)',
      'plan_biz_f1': '🏢 10 aktiv vakansiya yerləşdirmə',
      'plan_biz_f2': '✅ Təsdiqlənmiş Biznes (Verified) nişanı',
      'plan_biz_f3': '📊 Namizədlərin baxış və müraciət analitikası',
      'plan_biz_f4': '🚫 Reklamsız tətbiq istifadəsi',
      'plan_ent_name': 'Enterprise (\$49.99 / ay)',
      'plan_ent_f1': '♾️ Limitsiz vakansiya yerləşdirmə',
      'plan_ent_f2': '🌟 Hər ay 4 Pulsuz VIP Pin hədiyyə',
      'plan_ent_f3': '🎯 Şəxsi menecer və prioritet dəstək',
    },
    'ru': {
      'app_title': 'WorkSpot',
      'tag': '📍 Карта Вакансий',
      'subtitle': 'Находите вакансии рядом с вами на карте, просматривайте детали на месте и откликайтесь в один клик.',
      'phone_login': 'Вход по номеру телефона',
      'or_social': 'или через соцсети',
      'guest_login': 'Продолжить без аккаунта (Карта)',
      'terms': 'Входя в систему, вы принимаете Условия использования и Политику конфиденциальности WorkSpot.',
      'select_language': 'Выберите язык приложения',
      'search_hint': 'Поиск вакансии или компании...',
      'all': 'Все Вакансии',
      'cat_catering': 'Рестораны и Кафе',
      'cat_it': 'IT и Программирование',
      'cat_sales': 'Продажи и Маркетинг',
      'cat_logistics': 'Логистика и Доставка',
      'cat_customer_service': 'Обслуживание клиентов',
      'cat_construction': 'Строительство',
      'cat_education': 'Образование',
      'cat_medicine': 'Медицина и Здоровье',
      'cat_beauty': 'Салоны красоты',
      'radius_text': 'км радиус',
      'filter_title': 'Фильтры поиска',
      'reset': 'Сбросить',
      'search_radius': 'Радиус поиска:',
      'salary_range': 'Диапазон зарплат:',
      'job_modes': 'Режим работы:',
      'all_modes': 'Все режимы',
      'full_time': 'Полный рабочий день',
      'part_time': 'Частичная занятость',
      'remote': 'Удаленная работа',
      'apply_now': 'Откликнуться',
      'company_profile': 'Профиль компании',
      'salary_label': 'Зарплата:',
      'posted_label': 'Опубликовано:',
      'job_info': 'Информация о работе:',
      'found_jobs': 'Найденные вакансии',
      'no_jobs_found': 'Вакансий по вашему запросу не найдено.',
      'applied_msg': 'Ваш отклик успешно отправлен!',
      'satellite_mode': 'Спутник',
      'vector_mode': 'Карта',
      // PROFIL EKRANI SÖZLƏRİ:
      'profile_title': 'Личный Кабинет',
      'cv_status': 'Статус цифрового резюме',
      'update_cv': 'Обновить файл резюме',
      'stat_applications': 'Отклики',
      'stat_cv_views': 'Просмотренные резюме',
      'stat_favorites': 'Избранное',
      'my_applications': 'Отправленные заявки',
      'tab_all': 'Все',
      'tab_reviewed': 'Просмотренные',
      'tab_accepted': 'Принятые',
      'no_applications_yet': 'Вы еще не подавали заявку ни на одну вакансию.',
      'no_applications_sub': 'Изучите вакансии рядом с вами на карте и отправьте резюме в один клик.',
      'find_jobs_map': 'Искать работу на карте',
      'settings_title': 'Настройки',
      'notifications_title': 'Уведомления о вакансиях',
      'settings_notifications': 'Уведомления',
      'notifications_nearby_subtitle': 'Получать уведомления о новых вакансиях поблизости',
      'dark_mode': 'Тёмный режим (Dark Mode)',
      'notifications': 'Уведомления',
      'all_notifications': 'Все уведомления',
      'unread_notifications': 'Непрочитанные',
      'mark_all_read': 'Отметить все как прочитанные',
      'notifications_empty': 'Уведомлений нет',
      'notifications_unread_empty': 'Нет непрочитанных уведомлений',
      'notification_application_title': 'Ваше резюме просмотрено!',
      'notification_interview_title': 'Приглашение на собеседование 🎯',
      'notification_new_job_title': 'Новая вакансия рядом с вами 📍',
      'notification_system_title': 'Системное уведомление',
      'notification_application_message': 'Компания {company} просмотрела ваш отклик на вакансию "{job}".',
      'notification_interview_message': 'Компания {company} приглашает вас на онлайн-собеседование по вакансии "{job}".',
      'notification_new_job_message': 'Рядом с вами (500 м) опубликована новая вакансия "{job}".',
      'notification_system_message': 'Заполните данные профиля в WorkSpot, чтобы привлечь внимание большего числа работодателей.',
      'time_10_minutes': '10 мин назад',
      'time_2_hours': '2 часа назад',
      'time_yesterday': 'Вчера',
      'time_3_days': '3 дня назад',
      'logout': 'Выйти',
      'add_vacancy': 'Добавить новую вакансию',
      'job_title_required': 'Название вакансии *',
      'company_place_required': 'Название компании / места *',
      'category_label': 'Категория',
      'job_type_label': 'Режим работы',
      'salary_required': 'Зарплата (AZN) *',
      'shift_work': 'Посменная работа',
      'daily_work': 'Ежедневная работа',
      'hourly_flexible': 'Почасовая / Гибкий график',
      'remote_work': 'Удалённая работа',
      'vip_publish': 'Опубликовать как VIP',
      'vip_subtitle': 'Выделяется золотистым цветом вверху карты',
      'select_location': 'Выберите место работы на карте (Нажмите на карту):',
      'selected_coordinate': 'Выбранные координаты:',
      'publish_vacancy': 'Опубликовать вакансию',
      'view_details': 'Подробнее',
      'city_baku': 'Баку',
      'status_new': 'Новое',
      'no_description': 'Описание отсутствует.',
      'edit_profile': 'Редактировать профиль',
      // BİZNES / ÖDƏNİŞ EKRANI SÖZLƏRİ:
      'vip_biznes_button': 'VIP Бизнес',
      'biznes_packages_title': 'WorkSpot Бизнес и Пакеты',
      'biznes_packages_subtitle': 'VIP объявления и Pro подписка',
      'checkout_title': 'Выбор пакета',
      'checkout_b2b_section': 'B2B VIP Пакеты',
      'checkout_pro_section': 'Pro Подписка',
      'pkg_single_vip_pin': 'Один VIP Пин (еженедельно)',
      'pkg_pro_business': 'Пакет Pro Business (ежемесячно)',
      'pkg_enterprise': 'Пакет Enterprise (ежемесячно)',
      'pkg_pro_subscription': 'Pro Подписка (ежемесячно)',
      'vip_days_suffix': 'дней VIP',
      'select_package': 'Выберите пакет',
      'pay_with_pos': 'Оплатить через POS',
      'subscribe_now': 'Подписаться',
      'payment_confirmed_title': 'Оплата подтверждена',
      'receipt_package_label': 'Пакет',
      'receipt_amount_label': 'Сумма',
      'receipt_method_label': 'Способ оплаты',
      'receipt_transaction_label': 'Номер транзакции',
      'receipt_vip_expiry_label': 'Дата окончания VIP',
      'download_receipt': 'Скачать чек',
      'request_e_invoice': 'Запросить e-Qaimə',
      'close_label': 'Закрыть',
      'receipt_download_placeholder': 'Скачивание чека будет доступно в ближайшее время.',
      'e_invoice_placeholder': 'Запрос e-Qaimə зарегистрирован.',
      'payment_method_local_pos': 'Локальный POS (Карта)',
      'payment_method_apple_iap': 'Apple In-App Purchase',
      'payment_method_google_iap': 'Google In-App Purchase',
      'payment_success_message': 'Оплата успешно завершена.',
      'payment_failed_prefix': 'Оплата не выполнена:',
      // РОЛЬ / ПАНЕЛЬ БИЗНЕСА:
      'select_role_title': 'Как вы планируете использовать приложение?',
      'select_role_subtitle': 'Выберите тип профиля для продолжения',
      'role_candidate_title': 'Ищу работу',
      'role_candidate_desc': 'Находите вакансии на карте и откликайтесь в 1 клик',
      'role_employer_title': 'Ищу сотрудников / Компания',
      'role_employer_desc': 'Размещайте вакансии и находите подходящих кандидатов',
      'business_dashboard': 'Панель работодателя',
      'post_new_job': '+ Опубликовать вакансию',
      'my_active_jobs': 'Мои активные вакансии',
      'analytics_title': 'Аналитика кандидатов',
      'total_views': 'Всего просмотров',
      'total_applications': 'Количество откликов',
      'contact_views': 'Просмотры контактов',
      'upgrade_for_analytics': 'Перейдите на Pro Business для полной аналитики',
      'switch_to_map': 'Перейти к карте',
      'plan_standard_name': 'Стандарт (Бесплатно)',
      'plan_standard_f1': '📍 Поиск вакансий на карте',
      'plan_standard_f2': '🎬 Просмотр рекламы для отклика',
      'plan_pro_name': 'Pro (\$3.99 / мес)',
      'plan_pro_f1': '🚫 Полное отсутствие рекламы (No Ads)',
      'plan_pro_f2': '⚡ Мгновенный отклик в 1 клик',
      'plan_pro_f3': '🔔 Уведомления о новых вакансиях',
      'plan_vip_name': 'VIP Pin (\$8.99 / неделю)',
      'plan_vip_f1': '👑 Светящийся Золотой VIP Pin на карте',
      'plan_vip_f2': '🔝 Закрепление вверху списка',
      'plan_vip_f3': '📈 В 3 раза больше откликов',
      'plan_biz_name': 'Pro Business (\$22.99 / мес)',
      'plan_biz_f1': '🏢 Размещение до 10 активных вакансий',
      'plan_biz_f2': '✅ Значок Проверенного Бизнеса (Verified)',
      'plan_biz_f3': '📊 Полная аналитика просмотров и откликов',
      'plan_biz_f4': '🚫 Использование приложения без рекламы',
      'plan_ent_name': 'Enterprise (\$49.99 / мес)',
      'plan_ent_f1': '♾️ Безлимитное размещение вакансий',
      'plan_ent_f2': '🌟 4 бесплатные VIP Pin каждый месяц',
      'plan_ent_f3': '🎯 Личный менеджер и приоритетная поддержка',
    },
    'en': {
      'app_title': 'WorkSpot',
      'tag': '📍 Job Map',
      'subtitle': 'Discover job vacancies near you on the map, view details on the spot, and apply with one click.',
      'phone_login': 'Sign in with Phone Number',
      'or_social': 'or with social media',
      'guest_login': 'Continue as Guest (Explore Map)',
      'terms': 'By signing in, you agree to WorkSpot\'s Terms of Service and Privacy Policy.',
      'select_language': 'Select App Language',
      'search_hint': 'Search for jobs or companies...',
      'all': 'All Jobs',
      'cat_catering': 'Catering & Restaurants',
      'cat_it': 'IT & Software',
      'cat_sales': 'Sales & Marketing',
      'cat_logistics': 'Logistics & Delivery',
      'cat_customer_service': 'Customer Service',
      'cat_construction': 'Construction',
      'cat_education': 'Education',
      'cat_medicine': 'Medicine & Healthcare',
      'cat_beauty': 'Beauty & Spa',
      'radius_text': 'km radius',
      'filter_title': 'Search Filters',
      'reset': 'Reset',
      'search_radius': 'Search Radius:',
      'salary_range': 'Salary Range:',
      'job_modes': 'Job Mode:',
      'all_modes': 'All Modes',
      'full_time': 'Full-time',
      'part_time': 'Part-time',
      'remote': 'Remote',
      'apply_now': 'Apply Now',
      'company_profile': 'Company Profile',
      'salary_label': 'Salary:',
      'posted_label': 'Posted:',
      'job_info': 'Job Details:',
      'found_jobs': 'Found Vacancies',
      'no_jobs_found': 'No vacancies matched your filters.',
      'applied_msg': 'Your application was sent successfully!',
      'satellite_mode': 'Satellite Mode',
      'vector_mode': 'Map Mode',
      // PROFIL EKRANI SÖZLƏRİ:
      'profile_title': 'Personal Profile',
      'cv_status': 'Digital CV Status',
      'update_cv': 'Update CV File',
      'stat_applications': 'Applications',
      'stat_cv_views': 'Viewed CVs',
      'stat_favorites': 'Saved Jobs',
      'my_applications': 'Sent Applications',
      'tab_all': 'All',
      'tab_reviewed': 'Reviewed',
      'tab_accepted': 'Accepted',
      'no_applications_yet': 'You haven\'t applied for any jobs yet.',
      'no_applications_sub': 'Explore jobs near you on the map and send your CV with a single click.',
      'find_jobs_map': 'Search Jobs on Map',
      'settings_title': 'Settings',
      'notifications_title': 'Notifications',
      'settings_notifications': 'Notifications',
      'notifications_nearby_subtitle': 'Receive notifications when new jobs appear nearby',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'all_notifications': 'All notifications',
      'unread_notifications': 'Unread',
      'mark_all_read': 'Mark all as read',
      'notifications_empty': 'No notifications found',
      'notifications_unread_empty': 'You have no unread notifications',
      'notification_application_title': 'Your CV was viewed!',
      'notification_interview_title': 'Interview Invitation 🎯',
      'notification_new_job_title': 'New Job Near You 📍',
      'notification_system_title': 'System Notification',
      'notification_application_message': '{company} viewed your application for the "{job}" position.',
      'notification_interview_message': '{company} is inviting you to an online interview for the "{job}" position.',
      'notification_new_job_message': 'A new "{job}" job was posted near you (500m away).',
      'notification_system_message': 'Complete your WorkSpot profile to attract the attention of more employers.',
      'time_10_minutes': '10 mins ago',
      'time_2_hours': '2 hours ago',
      'time_yesterday': 'Yesterday',
      'time_3_days': '3 days ago',
      'logout': 'Logout',
      'add_vacancy': 'Add New Vacancy',
      'job_title_required': 'Job Title *',
      'company_place_required': 'Company / Place Name *',
      'category_label': 'Category',
      'job_type_label': 'Job Type',
      'salary_required': 'Salary (AZN) *',
      'shift_work': 'Shift work',
      'daily_work': 'Daily work',
      'hourly_flexible': 'Hourly / Flexible',
      'remote_work': 'Remote',
      'vip_publish': 'Publish as VIP Job',
      'vip_subtitle': 'Highlighted in gold on top of the map',
      'select_location': 'Select Job Location on Map (Tap map):',
      'selected_coordinate': 'Selected coordinate:',
      'publish_vacancy': 'Publish Vacancy',
      'view_details': 'View Details',
      'city_baku': 'Baku',
      'status_new': 'New',
      'no_description': 'No description available.',
      'edit_profile': 'Edit Profile',
      // BİZNES / ÖDƏNİŞ EKRANI SÖZLƏRİ:
      'vip_biznes_button': 'VIP Business',
      'biznes_packages_title': 'WorkSpot Business & Packages',
      'biznes_packages_subtitle': 'VIP listings and Pro subscription',
      'checkout_title': 'Choose a Package',
      'checkout_b2b_section': 'B2B VIP Packages',
      'checkout_pro_section': 'Pro Subscription',
      'pkg_single_vip_pin': 'Single VIP Pin (weekly)',
      'pkg_pro_business': 'Pro Business Package (monthly)',
      'pkg_enterprise': 'Enterprise Package (monthly)',
      'pkg_pro_subscription': 'Pro Subscription (monthly)',
      'vip_days_suffix': 'days VIP',
      'select_package': 'Select a package',
      'pay_with_pos': 'Pay with POS',
      'subscribe_now': 'Subscribe',
      'payment_confirmed_title': 'Payment Confirmed',
      'receipt_package_label': 'Package',
      'receipt_amount_label': 'Amount',
      'receipt_method_label': 'Payment Method',
      'receipt_transaction_label': 'Transaction No.',
      'receipt_vip_expiry_label': 'VIP Expiry Date',
      'download_receipt': 'Download Receipt',
      'request_e_invoice': 'Request e-Invoice',
      'close_label': 'Close',
      'receipt_download_placeholder': 'Receipt download will be available soon.',
      'e_invoice_placeholder': 'e-Invoice request has been recorded.',
      'payment_method_local_pos': 'Local POS (Card)',
      'payment_method_apple_iap': 'Apple In-App Purchase',
      'payment_method_google_iap': 'Google In-App Purchase',
      'payment_success_message': 'Payment completed successfully.',
      'payment_failed_prefix': 'Payment failed:',
      // ROLE SELECTION / BUSINESS DASHBOARD:
      'select_role_title': 'How do you plan to use the app?',
      'select_role_subtitle': 'Choose your profile type to continue',
      'role_candidate_title': 'Looking for a Job',
      'role_candidate_desc': 'Discover vacancies on the map and apply in 1 click',
      'role_employer_title': 'Hiring / Business',
      'role_employer_desc': 'Post vacancies and find suitable candidates',
      'business_dashboard': 'Employer Dashboard',
      'post_new_job': '+ Post New Job',
      'my_active_jobs': 'My Active Jobs',
      'analytics_title': 'Candidate Analytics',
      'total_views': 'Total Views',
      'total_applications': 'Applications',
      'contact_views': 'Contact Views',
      'upgrade_for_analytics': 'Upgrade to Pro Business for full analytics',
      'switch_to_map': 'Switch to Map View',
      'plan_standard_name': 'Standard (Free)',
      'plan_standard_f1': '📍 Discover job posts on map',
      'plan_standard_f2': '🎬 Watch rewarded ad to apply',
      'plan_pro_name': 'Pro (\$3.99 / mo)',
      'plan_pro_f1': '🚫 Completely Ad-Free experience',
      'plan_pro_f2': '⚡ Instant 1-click apply',
      'plan_pro_f3': '🔔 Instant job alert notifications',
      'plan_vip_name': 'VIP Pin (\$8.99 / week)',
      'plan_vip_f1': '👑 Glowing Gold VIP Pin on map',
      'plan_vip_f2': '🔝 Top placement in search & feeds',
      'plan_vip_f3': '📈 3x more candidate reach',
      'plan_biz_name': 'Pro Business (\$22.99 / mo)',
      'plan_biz_f1': '🏢 Post up to 10 active vacancies',
      'plan_biz_f2': '✅ Verified Business Badge',
      'plan_biz_f3': '📊 Candidate view & application analytics',
      'plan_biz_f4': '🚫 Ad-free platform usage',
      'plan_ent_name': 'Enterprise (\$49.99 / mo)',
      'plan_ent_f1': '♾️ Unlimited job postings',
      'plan_ent_f2': '🌟 4 Free VIP Pins every month',
      'plan_ent_f3': '🎯 Dedicated manager & priority support',
    },
  };

  String translate(String key) {
    return _localizedValues[_currentLanguage]?[key] ?? key;
  }
}

final appLang = AppLanguage();