import 'package:flutter/material.dart';

class AppLanguage extends ChangeNotifier {
  String _currentLanguage = 'az';

  String get currentLanguage => _currentLanguage;

  void changeLanguage(String langCode) {
    if (_currentLanguage != langCode) {
      _currentLanguage = langCode;
      notifyListeners();
    }
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'az': {
      'app_title': 'WorkSpot',
      'tag': '📍 İş Elanları Xəritəsi',
      'subtitle': 'Xəritə üzərindən sizə ən yaxın iş elanlarını kəşf edin, vakansiyaları yerindəcə görün və bir kliklə müraciət edin.',
      'phone_login': 'Telefon Nömrəsi ilə Giriş',
      'or_social': 'və ya sosial şəbəkə ilə',
      'guest_login': 'Hesabsız davam et (Xəritəni kəşf et)',
      'terms': 'Daxil olmaqla WorkSpot-un İstifadə Şərtlərini və Məxfilik Siyasətini qəbul etdiyinizi təsdiqləyirsiniz.',
      'select_language': 'Tətbiq Dilini Seçin',
      'search_hint': 'Vakansiya və ya şirkət axtarın...',
      'all': 'Bütün Vakansiyalar',
      'cat_catering': 'Restoran & Kafeler',
      'cat_it': 'İT & Proqramlaşdırma',
      'cat_sales': 'Satış & Marketinq',
      'cat_logistics': 'Logistika & Çatdırılma',
      'cat_customer_service': 'Müştəri Xidmətləri',
      'cat_construction': 'Tikinti & Təmir',
      'cat_education': 'Təhsil & Tədris',
      'cat_medicine': 'Səhiyyə & Tibb',
      'cat_beauty': 'Gözəllik & Salonda İş',
      'radius_text': 'km radiusda',
      'filter_title': 'Axtarış Filterləri',
      'reset': 'Sıfırla',
      'search_radius': 'Axtarış Radiusu:',
      'salary_range': 'Maaş Aralığı:',
      'job_modes': 'İş Rejimi:',
      'all_modes': 'Bütün Rejimlər',
      'full_time': 'Tam İş Qrafiki',
      'part_time': 'Yarım İş Qrafiki',
      'remote': 'Məsafədən (Remote)',
      'apply_now': 'Müraciət Et',
      'company_profile': 'Şirkət Profili',
      'salary_label': 'Əmək Haqqı:',
      'posted_label': 'Yayımlanıb:',
      'job_info': 'İş Barədə Məlumat:',
      'found_jobs': 'Tapılan Vakansiyalar',
      'no_jobs_found': 'Bu filterə uyğun vakansiya tapılmadı.',
      'applied_msg': 'vakansiyasına müraciətiniz göndərildi!',
      'satellite_mode': 'Peyk Rejimi',
      'vector_mode': 'Xəritə Rejimi',
      // PROFIL EKRANI SÖZLƏRİ:
      'profile_title': 'Şəxsi Kabinet',
      'cv_status': 'Rəqəmsal CV statusu',
      'update_cv': 'CV Faylını Yenilə',
      'stat_applications': 'Müraciətlər',
      'stat_cv_views': 'Baxılan CV-lər',
      'stat_favorites': 'Bəyənilənlər',
      'my_applications': 'Göndərdiyim Müraciətlər',
      'tab_all': 'Hamısı',
      'tab_reviewed': 'Baxılanlar',
      'tab_accepted': 'Qəbul Edilənlər',
      'no_applications_yet': 'Hələ ki hiç bir vakansiyaya müraciət etməmisiniz.',
      'no_applications_sub': 'Xəritəyə keçid edərək sizə ən yaxın iş elanlarını kəşf edin və bir kliklə CV-nizi göndərin.',
      'find_jobs_map': 'Xəritədə İş Axtar',
      'settings_title': 'Tənzimləmələr',
      'dark_mode': 'Qaranlıq Rejim (Dark Mode)',
      'notifications': 'Bildirişlər',
      'logout': 'Hesabdan Çıxış',
      'edit_profile': 'Profili Redaktə Et',
    },
    'ru': {
      'app_title': 'WorkSpot',
      'tag': '📍 Карта Вакансий',
      'subtitle': 'Находите вакансии рядом с вами на карте, просматривайте детали на месте и откликайтесь в один клик.',
      'phone_login': 'Вход по номеру телефона',
      'or_social': 'или через соцсети',
      'guest_login': 'Продолжить без аккаунта (Карта)',
      'terms': 'Входя в систему, вы принимаете Условия использования и Политику конфиденциальности WorkSpot.',
      'select_language': 'Выберите язык приложения',
      'search_hint': 'Поиск вакансии или компании...',
      'all': 'Все Вакансии',
      'cat_catering': 'Рестораны и Кафе',
      'cat_it': 'IT и Программирование',
      'cat_sales': 'Продажи и Маркетинг',
      'cat_logistics': 'Логистика и Доставка',
      'cat_customer_service': 'Обслуживание клиентов',
      'cat_construction': 'Строительство',
      'cat_education': 'Образование',
      'cat_medicine': 'Медицина и Здоровье',
      'cat_beauty': 'Салоны красоты',
      'radius_text': 'км радиус',
      'filter_title': 'Фильтры поиска',
      'reset': 'Сбросить',
      'search_radius': 'Радиус поиска:',
      'salary_range': 'Диапазон зарплат:',
      'job_modes': 'Режим работы:',
      'all_modes': 'Все режимы',
      'full_time': 'Полный рабочий день',
      'part_time': 'Частичная занятость',
      'remote': 'Удаленная работа',
      'apply_now': 'Откликнуться',
      'company_profile': 'Профиль компании',
      'salary_label': 'Зарплата:',
      'posted_label': 'Опубликовано:',
      'job_info': 'Информация о работе:',
      'found_jobs': 'Найденные вакансии',
      'no_jobs_found': 'Вакансий по вашему запросу не найдено.',
      'applied_msg': 'Ваш отклик успешно отправлен!',
      'satellite_mode': 'Спутник',
      'vector_mode': 'Карта',
      // PROFIL EKRANI SÖZLƏRİ:
      'profile_title': 'Личный Кабинет',
      'cv_status': 'Статус цифрового резюме',
      'update_cv': 'Обновить файл CV',
      'stat_applications': 'Отклики',
      'stat_cv_views': 'Просмотры CV',
      'stat_favorites': 'Избранное',
      'my_applications': 'Мои Отклики',
      'tab_all': 'Все',
      'tab_reviewed': 'Просмотрено',
      'tab_accepted': 'Принято',
      'no_applications_yet': 'Вы еще не откликались ни на одну вакансию.',
      'no_applications_sub': 'Перейдите на карту, чтобы найти ближайшие вакансии и отправить CV в один клик.',
      'find_jobs_map': 'Искать на карте',
      'settings_title': 'Настройки',
      'dark_mode': 'Тёмный режим (Dark Mode)',
      'notifications': 'Уведомления',
      'logout': 'Выйти из аккаунта',
      'edit_profile': 'Редактировать профиль',
    },
    'en': {
      'app_title': 'WorkSpot',
      'tag': '📍 Job Map',
      'subtitle': 'Discover job vacancies near you on the map, view details on the spot, and apply with one click.',
      'phone_login': 'Sign in with Phone Number',
      'or_social': 'or with social media',
      'guest_login': 'Continue as Guest (Explore Map)',
      'terms': 'By signing in, you agree to WorkSpot\'s Terms of Service and Privacy Policy.',
      'select_language': 'Select App Language',
      'search_hint': 'Search for jobs or companies...',
      'all': 'All Jobs',
      'cat_catering': 'Catering & Restaurants',
      'cat_it': 'IT & Software',
      'cat_sales': 'Sales & Marketing',
      'cat_logistics': 'Logistics & Delivery',
      'cat_customer_service': 'Customer Service',
      'cat_construction': 'Construction',
      'cat_education': 'Education',
      'cat_medicine': 'Medicine & Healthcare',
      'cat_beauty': 'Beauty & Spa',
      'radius_text': 'km radius',
      'filter_title': 'Search Filters',
      'reset': 'Reset',
      'search_radius': 'Search Radius:',
      'salary_range': 'Salary Range:',
      'job_modes': 'Job Mode:',
      'all_modes': 'All Modes',
      'full_time': 'Full-time',
      'part_time': 'Part-time',
      'remote': 'Remote',
      'apply_now': 'Apply Now',
      'company_profile': 'Company Profile',
      'salary_label': 'Salary:',
      'posted_label': 'Posted:',
      'job_info': 'Job Details:',
      'found_jobs': 'Found Vacancies',
      'no_jobs_found': 'No vacancies matched your filters.',
      'applied_msg': 'Your application was sent successfully!',
      'satellite_mode': 'Satellite Mode',
      'vector_mode': 'Map Mode',
      // PROFIL EKRANI SÖZLƏRİ:
      'profile_title': 'Personal Profile',
      'cv_status': 'Digital CV Status',
      'update_cv': 'Update CV File',
      'stat_applications': 'Applications',
      'stat_cv_views': 'CV Views',
      'stat_favorites': 'Saved Jobs',
      'my_applications': 'My Applications',
      'tab_all': 'All',
      'tab_reviewed': 'Reviewed',
      'tab_accepted': 'Accepted',
      'no_applications_yet': 'You haven\'t applied to any jobs yet.',
      'no_applications_sub': 'Switch to the map to discover nearby vacancies and send your CV in one click.',
      'find_jobs_map': 'Find Jobs on Map',
      'settings_title': 'Settings',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'logout': 'Log Out',
      'edit_profile': 'Edit Profile',
    },
  };

  String translate(String key) {
    return _localizedValues[_currentLanguage]?[key] ?? key;
  }
}

final appLang = AppLanguage();