import 'package:supabase_flutter/supabase_flutter.dart';

class JobSeedService {
  static final SupabaseClient _client = Supabase.instance.client;

  static double _parseSalaryAmount(String raw) {
    final cleaned = raw.replaceAll(RegExp(r'[^0-9.,-]'), '');
    if (cleaned.isEmpty) return 0.0;

    final normalized = cleaned.replaceAll(',', '.');
    final firstValue = normalized.split('-').first.trim();
    return double.tryParse(firstValue) ?? 0.0;
  }

  static Future<void> seedMockJobs() async {
    final mockJobs = [
      {
        'title': 'Barista / Kofe Mütəxəssisi',
        'company_name': 'Urban Cafe 28',
        'category': 'Kafe & Restoran',
        'salary': '600 - 800 AZN',
        'salary_amount': '600 - 800 AZN',
        'job_type': 'Tam iş günü',
        'employment_type': 'Tam iş günü',
        'address': '28 May küç., 28 Mall yaxınlığı',
        'location': '28 May küç., 28 Mall yaxınlığı',
        'latitude': 40.3798,
        'longitude': 49.8472,
        'description': 'Aktiv, mehriban və kofe hazırlamağı sevən barista axtarılır.',
        'image_url': 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Kassir',
        'company_name': 'Baku Book & Stationery',
        'category': 'Satış & Retail',
        'salary': '550 - 650 AZN',
        'salary_amount': '550 - 650 AZN',
        'job_type': 'Tam iş günü',
        'employment_type': 'Tam iş günü',
        'address': '28 May m/s çıxışı',
        'location': '28 May m/s çıxışı',
        'latitude': 40.3805,
        'longitude': 49.8490,
        'description': 'Kassa aparatları ilə işləyə bilən diqqətli əməkdaş.',
        'image_url': 'https://images.unsplash.com/photo-1556742049-0a670f4a4591',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Florist / Çiçək Dizayneri',
        'company_name': 'Rose Boutique',
        'category': 'Xidmət & Dizayn',
        'salary': '600 - 900 AZN',
        'salary_amount': '600 - 900 AZN',
        'job_type': 'Tam iş günü',
        'employment_type': 'Tam iş günü',
        'address': 'Rəşid Behbudov küç.',
        'location': 'Rəşid Behbudov küç.',
        'latitude': 40.3770,
        'longitude': 49.8420,
        'description': 'Gül buketlərinin və kompozisiyalarının yığılması.',
        'image_url': 'https://images.unsplash.com/photo-1561181286-d3fee7d55364',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Satıcı-Məsləhətçi',
        'company_name': 'Trendy Fashion Store',
        'category': 'Satış & Retail',
        'salary': '500 - 700 AZN + %',
        'salary_amount': '500 - 700 AZN + %',
        'job_type': 'Növbəli',
        'employment_type': 'Növbəli',
        'address': 'Nizami küç. (Torqovaya)',
        'location': 'Nizami küç. (Torqovaya)',
        'latitude': 40.3712,
        'longitude': 49.8372,
        'description': 'Geyim mağazasına aktiv satış təmsilçisi tələb olunur.',
        'image_url': 'https://images.unsplash.com/photo-1441986300917-64674bd600d8',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Hostess / Qonaq Qarşılayan',
        'company_name': 'Anadolu Restaurant',
        'category': 'Kafe & Restoran',
        'salary': '600 - 750 AZN',
        'salary_amount': '600 - 750 AZN',
        'job_type': 'Növbəli',
        'employment_type': 'Növbəli',
        'address': 'Puşkin küç., Sahil m/s',
        'location': 'Puşkin küç., Sahil m/s',
        'latitude': 40.3705,
        'longitude': 49.8450,
        'description': 'Restorana gələn qonaqların qarşılanması və masalara yönləndirilməsi.',
        'image_url': 'https://images.unsplash.com/photo-1560066984-138dadb4c035',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Qəlyanaltı / Fast Food Ustası',
        'company_name': 'Burger House',
        'category': 'Kafe & Restoran',
        'salary': '650 - 800 AZN',
        'salary_amount': '650 - 800 AZN',
        'job_type': 'Tam iş günü',
        'employment_type': 'Tam iş günü',
        'address': 'Fəvvarələr Meydanı',
        'location': 'Fəvvarələr Meydanı',
        'latitude': 40.3725,
        'longitude': 49.8360,
        'description': 'Burger və fast-food təamlarının hazırlanması.',
        'image_url': 'https://images.unsplash.com/photo-1550547660-d9450f859349',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Ofisiant (Part-time)',
        'company_name': 'Coffee Moffie',
        'category': 'Kafe & Restoran',
        'salary': '400 - 600 AZN + Çay pulu',
        'salary_amount': '400 - 600 AZN + Çay pulu',
        'job_type': 'Yarım iş günü',
        'employment_type': 'Yarım iş günü',
        'address': 'Elmlər Akademiyası m/s yaxınlığı',
        'location': 'Elmlər Akademiyası m/s yaxınlığı',
        'latitude': 40.3745,
        'longitude': 49.8135,
        'description': 'Tələbələr üçün dərslərdən sonra 4-5 saatlıq rahat iş qrafiki.',
        'image_url': 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Kopyalama və Print Operatoru',
        'company_name': 'Copy Center Elmlər',
        'category': 'Xidmət',
        'salary': '450 - 550 AZN',
        'salary_amount': '450 - 550 AZN',
        'job_type': 'Növbəli',
        'employment_type': 'Növbəli',
        'address': 'Hüseyn Cavid pr.',
        'location': 'Hüseyn Cavid pr.',
        'latitude': 40.3720,
        'longitude': 49.8150,
        'description': 'Tələbə sənədlərinin çapı və kopyalanması xidməti.',
        'image_url': 'https://images.unsplash.com/photo-1562654501-a0ccc0fc3fb1',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Piyada Kuryer',
        'company_name': 'Express Delivery',
        'category': 'Çatdırılma',
        'salary': '600 - 900 AZN',
        'salary_amount': '600 - 900 AZN',
        'job_type': 'Sərbəst qrafik',
        'employment_type': 'Sərbəst qrafik',
        'address': 'Nəriman Nərimanov m/s',
        'location': 'Nəriman Nərimanov m/s',
        'latitude': 40.4028,
        'longitude': 49.8711,
        'description': 'Şəhər mərkəzində kiçik bağlamaların çatdırılması.',
        'image_url': 'https://images.unsplash.com/photo-1526367790999-0150786686a2',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'SMM & Kontent Menecer',
        'company_name': 'Creative Agency Studio',
        'category': 'Marketing / Media',
        'salary': '700 - 1000 AZN',
        'salary_amount': '700 - 1000 AZN',
        'job_type': 'Hibrid',
        'employment_type': 'Hibrid',
        'address': 'Təbriz küç., Nərimanov',
        'location': 'Təbriz küç., Nərimanov',
        'latitude': 40.4050,
        'longitude': 49.8680,
        'description': 'Reels/TikTok kontentləri hazırlayacaq kreativ komanda üzvü.',
        'image_url': 'https://images.unsplash.com/photo-1531482615713-2afd69097998',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Məhsul Qablaşdırıcısı',
        'company_name': 'SuperMarket Network',
        'category': 'Anbar & Logistika',
        'salary': '500 - 600 AZN',
        'salary_amount': '500 - 600 AZN',
        'job_type': 'Tam iş günü',
        'employment_type': 'Tam iş günü',
        'address': 'Gənclik m/s, Atatürk pr.',
        'location': 'Gənclik m/s, Atatürk pr.',
        'latitude': 40.4001,
        'longitude': 49.8523,
        'description': 'Vitrinlərin düzülməsi və məhsulların qablaşdırılması.',
        'image_url': 'https://images.unsplash.com/photo-1578916171728-46686eac8d58',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Fitness Konsultant',
        'company_name': 'Ganjlik Gym & Sport',
        'category': 'İdman & Sağlamlıq',
        'salary': '600 - 850 AZN',
        'salary_amount': '600 - 850 AZN',
        'job_type': 'Növbəli',
        'employment_type': 'Növbəli',
        'address': 'Gənclik Mall yaxınlığı',
        'location': 'Gənclik Mall yaxınlığı',
        'latitude': 40.3980,
        'longitude': 49.8550,
        'description': 'Zala gelen müştərilərin qarşılanması və abunəlik satışı.',
        'image_url': 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Resepsionist',
        'company_name': 'City Beauty Studio',
        'category': 'Xidmət',
        'salary': '600 - 750 AZN',
        'salary_amount': '600 - 750 AZN',
        'job_type': 'Növbəli',
        'employment_type': 'Növbəli',
        'address': 'İçərişəhər m/s yaxınlığı',
        'location': 'İçərişəhər m/s yaxınlığı',
        'latitude': 40.3661,
        'longitude': 49.8322,
        'description': 'Gözəllik salonuna qonaqları qarşılayacaq əməkdaş.',
        'image_url': 'https://images.unsplash.com/photo-1560066984-138dadb4c035',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Qrafik Dizayner (Junior)',
        'company_name': 'Print Art Baku',
        'category': 'Dizayn',
        'salary': '500 - 700 AZN',
        'salary_amount': '500 - 700 AZN',
        'job_type': 'Tam iş günü',
        'employment_type': 'Tam iş günü',
        'address': 'Nizami m/s, Cəfər Cabbarlı',
        'location': 'Nizami m/s, Cəfər Cabbarlı',
        'latitude': 40.3790,
        'longitude': 49.8280,
        'description': 'Sosial media postlarının və reklam banerlərinin hazırlanması.',
        'image_url': 'https://images.unsplash.com/photo-1626785774573-4b799315345d',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Satış Təmsilçisi',
        'company_name': 'Auto Care Center',
        'category': 'Avto & Xidmət',
        'salary': '700 - 1000 AZN',
        'salary_amount': '700 - 1000 AZN',
        'job_type': 'Tam iş günü',
        'employment_type': 'Tam iş günü',
        'address': 'Xətai m/s, Xocalı pr.',
        'location': 'Xətai m/s, Xocalı pr.',
        'latitude': 40.3830,
        'longitude': 49.8720,
        'description': 'Avto aksesuarların və ehtiyat hissələrinin satışı.',
        'image_url': 'https://images.unsplash.com/photo-1580273916550-e323be2ae537',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Ofis Meneceri',
        'company_name': 'White City Logistics',
        'category': 'Ofis & İnzibati',
        'salary': '700 - 900 AZN',
        'salary_amount': '700 - 900 AZN',
        'job_type': 'Tam iş günü',
        'employment_type': 'Tam iş günü',
        'address': 'Ağ Şəhər (White City)',
        'location': 'Ağ Şəhər (White City)',
        'latitude': 40.3775,
        'longitude': 49.8890,
        'description': 'Zənglərin cavablandırılması və ofis daxili sənədləşmə.',
        'image_url': 'https://images.unsplash.com/photo-1497366216548-37526070297c',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Aptek Satıcısı / Əczaçı',
        'company_name': 'Zəfəran Aptek',
        'category': 'Səhiyyə & Tibb',
        'salary': '600 - 800 AZN',
        'salary_amount': '600 - 800 AZN',
        'job_type': 'Növbəli',
        'employment_type': 'Növbəli',
        'address': 'İnşaatçılar m/s çıxışı',
        'location': 'İnşaatçılar m/s çıxışı',
        'latitude': 40.3890,
        'longitude': 49.8030,
        'description': 'Dərman vasitələrinin satışı və müştəri konsultasiyası.',
        'image_url': 'https://images.unsplash.com/photo-1586015555751-63c205a30620',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Call Center Operatoru',
        'company_name': 'Baku Telecom Partner',
        'category': 'Xidmət & Zəng Mərkəzi',
        'salary': '500 - 650 AZN',
        'salary_amount': '500 - 650 AZN',
        'job_type': 'Növbəli',
        'employment_type': 'Növbəli',
        'address': 'Yasamal, Şərifzadə küç.',
        'location': 'Yasamal, Şərifzadə küç.',
        'latitude': 40.3840,
        'longitude': 49.8080,
        'description': 'Gələn zənglərin qəbulu və sualların cavablandırılması.',
        'image_url': 'https://images.unsplash.com/photo-1534536281715-e28d76689b4d',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Anbar Fəhləsi / Anbardar',
        'company_name': 'Baku Depot Park',
        'category': 'Anbar & Logistika',
        'salary': '550 - 700 AZN',
        'salary_amount': '550 - 700 AZN',
        'job_type': 'Tam iş günü',
        'employment_type': 'Tam iş günü',
        'address': 'Koroğlu m/s yaxınlığı',
        'location': 'Koroğlu m/s yaxınlığı',
        'latitude': 40.4210,
        'longitude': 49.9180,
        'description': 'Anbara gələn malların qəbulu və boşaldılması.',
        'image_url': 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d',
        'status': 'active',
        'is_verified': true,
      },
      {
        'title': 'Avtoyuyan / Detailer',
        'company_name': 'VIP Car Wash',
        'category': 'Xidmət',
        'salary': '600 - 1000 AZN (Faizlə)',
        'salary_amount': '600 - 1000 AZN (Faizlə)',
        'job_type': 'Tam iş günü',
        'employment_type': 'Tam iş günü',
        'address': 'Heydər Əliyev pr.',
        'location': 'Heydər Əliyev pr.',
        'latitude': 40.4120,
        'longitude': 49.9010,
        'description': 'Nəqliyyat vasitələrinin kimyəvi təmizlənməsi və yuyulması.',
        'image_url': 'https://images.unsplash.com/photo-1520340356584-f9917d1eea6f',
        'status': 'active',
        'is_verified': true,
      },
    ];

    try {
      final rows = mockJobs.map((job) {
        final salaryNumber = _parseSalaryAmount(job['salary_amount'].toString());
        return {
          'title': job['title'],
          'company_name': job['company_name'],
          'category': job['category'],
          'salary': job['salary'],
          'salary_amount': salaryNumber,
          'job_type': job['job_type'],
          'employment_type': job['employment_type'],
          'address': job['address'],
          'location': job['location'],
          'latitude': job['latitude'],
          'longitude': job['longitude'],
          'status': job['status'],
          'is_verified': job['is_verified'],
          'description': job['description'],
          'image_url': job['image_url'],
          'created_at': DateTime.now().toIso8601String(),
        };
      }).toList();

      await _client.from('jobs').insert(rows);
      print('✅ ${rows.length} demo jobs inserted into Supabase jobs table');
    } catch (error) {
      print('❌ Seed failed: $error');
      rethrow;
    }
  }
}
